import {
  addTypeTemplate,
  defineNuxtModule,
  createResolver,
  addServerHandler,
  addServerPlugin,
  addRouteMiddleware,
  addImportsDir,
  addServerImportsDir,
  addPlugin,
  extendRouteRules,
  resolvePath,
} from '@nuxt/kit';
import type { RouteConfig } from './types';

export * from './types';
export type { SessionConfiguration, SessionCookieOptions, StateData } from '@auth0/auth0-server-js';

/**
 * Module options for the Auth0 Nuxt module.
 */
export interface ModuleOptions {
  /**
   * Mount the Auth0 routes in the Nuxt server.
   * If set to false, you will need to manually mount the routes in your Nuxt server.
   * @default true
   */
  mountRoutes?: boolean;

  /**
   * The route URLs to use for the Auth0 module.
   * You can override the default routes by providing your own configuration.
   * @default { login: '/auth/login', callback: '/auth/callback', logout: '/auth/logout', backchannelLogout: '/auth/backchannel-logout', profile: '/auth/profile' }
   */
  routes?: RouteConfig;

  /**
   * Whether to populate `useUser()` during server-side rendering, which Nuxt serializes into
   * the `__NUXT__` payload of the rendered HTML.
   *
   * Set to `false` to keep every server-rendered page anonymous; the user is hydrated
   * client-side from the profile endpoint instead. A per-route `auth0: { ssrUser: … }` route
   * rule overrides this default, so you can opt out globally and opt individual routes back in.
   *
   * This SDK cannot detect how your responses are cached — `Cache-Control` set at request
   * time and CDN-side configuration are both invisible to it — so if you serve authenticated
   * routes from a shared cache, opt those routes out yourself.
   *
   * Note that an opted-out route cannot be protected by route middleware that checks
   * `useUser()`: there is no user during SSR, so such middleware would redirect a signed-in
   * user to the login route and Auth0 would return them to the same route, looping. Protect
   * these routes with server middleware reading the session from the H3 event instead.
   * @default true
   */
  ssrUser?: boolean;

  /**
   * Path to a custom session store factory.
   * This allows you to provide a custom session store implementation to use stateful sessions.
   * The factory should default export a function that returns an object with the methods required by the Auth0 session store.
   * If not provided, the SDK will use stateless sessions and store everything in the cookie.
   */
  sessionStoreFactoryPath?: string;
}

/**
 * The `auth0` route-rule declaration handed to the consuming app, written verbatim to
 * `.nuxt/types/auth0-route-rules.d.ts`.
 *
 * It lives at module scope because a template literal preserves its own indentation: nesting
 * it inside `setup` would indent every line of the generated file.
 *
 * Not `String.raw`: the backticks in the JSDoc below have to stay escaped or they would end
 * the template, and raw mode would emit the backslashes instead of consuming them.
 */
const ROUTE_RULES_DECLARATION = `// Generated by @auth0/auth0-nuxt
interface Auth0NitroRules {
  /**
   * Populate \`useUser()\` during server-side rendering for routes matching this rule.
   * Set to \`false\` to keep the route's HTML anonymous; the user is hydrated client-side
   * instead. Apply it to \`/**\` to opt out globally.
   * @default true
   */
  auth0?: { ssrUser?: boolean };
}

declare module 'nitropack/types' {
  interface NitroRouteRules extends Auth0NitroRules {}
  interface NitroRouteConfig extends Auth0NitroRules {}
}

export {};
`;

/**
 * @ignore
 */
export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'auth0-nuxt',
    configKey: 'auth0',
  },
  async setup(options, nuxt) {
    const resolver = createResolver(import.meta.url);

    // Registering the declaration with Nuxt is the only route a module's `declare module`
    // blocks have into a consumer's type program: `dist/types.d.mts` is reachable from the
    // config program, but nothing there pulls in a declaration file the package merely ships.
    //
    // The context decides which generated file gets the reference, and so which tsconfig
    // project sees it. All three are load-bearing:
    //   `node`  — `.nuxt/tsconfig.node.json` compiles `nuxt.config.*`, so without it the
    //             route rule is still an excess property where it is written.
    //   `nitro` — the server program, so an app reading `getRouteRules(event).auth0` in its
    //             own server code gets it typed rather than TS2339.
    //   `nuxt`  — the app program, and the default when no context is given.
    // On Nuxt 3, `node` is an unknown key that kit ignores. That is harmless: Nuxt 3 has a
    // single generated tsconfig which already picks up `nuxt.config.*`.
    addTypeTemplate(
      {
        filename: 'types/auth0-route-rules.d.ts',
        getContents: () => ROUTE_RULES_DECLARATION,
      },
      { nuxt: true, node: true, nitro: true }
    );

    if (options.sessionStoreFactoryPath) {
      nuxt.options.nitro.alias = nuxt.options.nitro.alias || {};
      nuxt.options.nitro.alias['#auth0-session-store'] = await resolvePath(options.sessionStoreFactoryPath);
    } else {
      nuxt.options.nitro.alias = nuxt.options.nitro.alias || {};
      nuxt.options.nitro.alias['#auth0-session-store'] = resolver.resolve(
        './runtime/server/utils/load-default-session-store'
      );
    }

    const defaultRoutes = {
      login: '/auth/login',
      callback: '/auth/callback',
      logout: '/auth/logout',
      backchannelLogout: '/auth/backchannel-logout',
      profile: '/auth/profile',
    };

    const routes: Required<RouteConfig> = {
      ...defaultRoutes,
      ...options.routes,
    };

    // Expose the routes in the public runtime config so that it can be accessed in both server and client contexts
    nuxt.options.runtimeConfig.public.auth0 = {
      routes,
      // The module-level SSR user-write default. The `auth.server` Nitro plugin applies it
      // when a route rule does not set its own `auth0.ssrUser`.
      ssrUser: options.ssrUser !== false,
    };

    addServerPlugin(resolver.resolve('./runtime/server/plugins/auth.server'));

    addRouteMiddleware({ name: 'auth0', path: resolver.resolve('./runtime/middleware/auth.server'), global: true });

    addPlugin(resolver.resolve('./runtime/plugins/auth.client'));

    // Nitro's handler cache keys by path and ignores the session cookie, so a broad rule like
    // `'/**': { swr: 60 }` would serve one user's claims to the next. The endpoint's own
    // `no-store` does not save us: Nitro overwrites it. Kept outside the `mountRoutes` guard
    // because Nitro reads this from the route a handler is registered at, so an app mounting
    // the handler itself needs the rule too (and its own, if it picks a different path).
    extendRouteRules(routes.profile, { cache: false }, { override: true });

    if (options?.mountRoutes !== false) {
      addServerHandler({
        handler: resolver.resolve('./runtime/server/api/auth/login.get'),
        route: routes.login,
        method: 'get',
      });

      addServerHandler({
        handler: resolver.resolve('./runtime/server/api/auth/callback.get'),
        route: routes.callback,
        method: 'get',
      });

      addServerHandler({
        handler: resolver.resolve('./runtime/server/api/auth/logout.get'),
        route: routes.logout,
        method: 'get',
      });

      addServerHandler({
        handler: resolver.resolve('./runtime/server/api/auth/backchannel-logout.post'),
        route: routes.backchannelLogout,
        method: 'post',
      });

      addServerHandler({
        handler: resolver.resolve('./runtime/server/api/auth/profile.get'),
        route: routes.profile,
        method: 'get',
      });
    }

    addImportsDir(resolver.resolve('./runtime/composables'));
    addServerImportsDir(resolver.resolve('./runtime/server/composables'));
  },
});
